export const BRAND_NAME = "Player One IQ";
export const BRAND_LOGO_VERSION = "3";
export const BRAND_LOGO_FILE = "/branding/p1iq-wordmark-transparent.png";
export const BRAND_LOGO_PATH = `${BRAND_LOGO_FILE}?v=${BRAND_LOGO_VERSION}`;
export const BRAND_LOGO_WIDTH = 614;
export const BRAND_LOGO_HEIGHT = 207;
export const BRAND_LOGO_ALT = "Player One IQ";
export const BRAND_FAVICON_VERSION = "10";
export const BRAND_FAVICON_PATH = `/favicon.ico?v=${BRAND_FAVICON_VERSION}`;
export const BRAND_MANIFEST_PATH = "/site.webmanifest";
